name: Build and Release Go Binary

on:
    push:
        tags:
            - "v*.*.*"

jobs:
    build-and-release:
        runs-on: ubuntu-latest
        strategy:
            matrix:
                goos: [linux, windows, darwin]
                goarch: [amd64, arm64]
                exclude:
                    - goarch: arm64
                      goos: windows
        steps:
            - uses: actions/checkout@v3

            - name: Build and Release
              uses: wangyoucao577/go-release-action@v1.30
              with:
                  github_token: ${{ secrets.GITHUB_TOKEN }}
                  goos: ${{ matrix.goos }}
                  goarch: ${{ matrix.goarch }}
                  goversion: "1.20"
                  binary_name: "quicknav"
                  extra_files: README.md
                  project_path: "."
                  build_flags: "-v"
                  ldflags: "-s -w"
                  pre_command: go mod tidy
                  md5sum: false
                  sha256sum: true

    update-release-draft:
        needs: build-and-release
        runs-on: ubuntu-latest
        steps:
            - uses: release-drafter/release-drafter@v5
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
