name: Build and Release Go Binary

on:
    push:
        tags:
            - "v*.*.*"

concurrency:
    group: ${{ github.workflow }}-${{ github.ref }}
    cancel-in-progress: false

jobs:
    build-and-release:
        runs-on: ubuntu-latest
        permissions: write-all
        strategy:
            matrix:
                goos: [linux, windows, darwin]
                goarch: [amd64, arm64]
        steps:
            - uses: actions/checkout@v4
            - run: git fetch --unshallow --quiet --tags --force

            - name: Set up Go
              uses: actions/setup-go@v5
              with:
                  go-version-file: go.mod
                  check-latest: true

            - name: Build
              env:
                  GOOS: ${{ matrix.goos }}
                  GOARCH: ${{ matrix.goarch }}
                  CGO_ENABLED: 1
              run: |
                  go mod tidy
                  go build -v -ldflags="-s -w -X main.version=${{ github.ref_name }}" -o quicknav-${{ matrix.goos }}-${{ matrix.goarch }}${{ matrix.goos == 'windows' && '.exe' || '' }}

            # Add a new step to install cross-compilation tools
            # - name: Set up cross-compilation
            #   run: |
            #       sudo apt-get update
            #       sudo apt-get install -y gcc-aarch64-linux-gnu gcc-mingw-w64-x86-64 gcc-darwin-x86-64

            - name: Package
              run: |
                  if [ "${{ matrix.goos }}" = "windows" ]; then
                      zip quicknav-${{ matrix.goos }}-${{ matrix.goarch }}.zip quicknav-${{ matrix.goos }}-${{ matrix.goarch }}.exe README.md
                  else
                      tar -czvf quicknav-${{ matrix.goos }}-${{ matrix.goarch }}.tar.gz quicknav-${{ matrix.goos }}-${{ matrix.goarch }} README.md
                  fi

            - name: Generate SHA256
              run: |
                  if [ "${{ matrix.goos }}" = "windows" ]; then
                      sha256sum quicknav-${{ matrix.goos }}-${{ matrix.goarch }}.zip > quicknav-${{ matrix.goos }}-${{ matrix.goarch }}.zip.sha256
                  else
                      sha256sum quicknav-${{ matrix.goos }}-${{ matrix.goarch }}.tar.gz > quicknav-${{ matrix.goos }}-${{ matrix.goarch }}.tar.gz.sha256
                  fi

            - name: Release
              uses: softprops/action-gh-release@v2
              if: startsWith(github.ref, 'refs/tags/')
              with:
                  files: |
                      quicknav-${{ matrix.goos }}-${{ matrix.goarch }}${{ matrix.goos == 'windows' && '.zip' || '.tar.gz' }}
                      quicknav-${{ matrix.goos }}-${{ matrix.goarch }}${{ matrix.goos == 'windows' && '.zip' || '.tar.gz' }}.sha256
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
